language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t behanboshoff/DockerReactAppCI -f Dockerfile.dev .

script:
  - docker run -e CI=true behanboshoff/DockerReactAppCI npm run test